/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'acclimationsupport' at '15/02/16 10:59 AM' with Gradle 2.11
 *
 * @author acclimationsupport, @date 15/02/16 10:59 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
